# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Thu Oct 27 21:50:27 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MyGame(object):
    def setupUi(self, MyGame):
        MyGame.setObjectName("MyGame")
        MyGame.resize(1272, 600)
        self.centralwidget = QtGui.QWidget(MyGame)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtGui.QLabel(self.widget_2)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.widget_5 = QtGui.QWidget(self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.b0 = QtGui.QPushButton(self.widget_5)
        self.b0.setObjectName("b0")
        self.gridLayout_4.addWidget(self.b0, 0, 0, 1, 1)
        self.b1 = QtGui.QPushButton(self.widget_5)
        self.b1.setObjectName("b1")
        self.gridLayout_4.addWidget(self.b1, 0, 1, 1, 1)
        self.b8 = QtGui.QPushButton(self.widget_5)
        self.b8.setObjectName("b8")
        self.gridLayout_4.addWidget(self.b8, 1, 3, 1, 1)
        self.b14 = QtGui.QPushButton(self.widget_5)
        self.b14.setObjectName("b14")
        self.gridLayout_4.addWidget(self.b14, 2, 4, 1, 1)
        self.b10 = QtGui.QPushButton(self.widget_5)
        self.b10.setObjectName("b10")
        self.gridLayout_4.addWidget(self.b10, 2, 0, 1, 1)
        self.b7 = QtGui.QPushButton(self.widget_5)
        self.b7.setObjectName("b7")
        self.gridLayout_4.addWidget(self.b7, 1, 2, 1, 1)
        self.b12 = QtGui.QPushButton(self.widget_5)
        self.b12.setObjectName("b12")
        self.gridLayout_4.addWidget(self.b12, 2, 2, 1, 1)
        self.b9 = QtGui.QPushButton(self.widget_5)
        self.b9.setObjectName("b9")
        self.gridLayout_4.addWidget(self.b9, 1, 4, 1, 1)
        self.b4 = QtGui.QPushButton(self.widget_5)
        self.b4.setObjectName("b4")
        self.gridLayout_4.addWidget(self.b4, 0, 4, 1, 1)
        self.b3 = QtGui.QPushButton(self.widget_5)
        self.b3.setObjectName("b3")
        self.gridLayout_4.addWidget(self.b3, 0, 3, 1, 1)
        self.b2 = QtGui.QPushButton(self.widget_5)
        self.b2.setObjectName("b2")
        self.gridLayout_4.addWidget(self.b2, 0, 2, 1, 1)
        self.b6 = QtGui.QPushButton(self.widget_5)
        self.b6.setObjectName("b6")
        self.gridLayout_4.addWidget(self.b6, 1, 1, 1, 1)
        self.b11 = QtGui.QPushButton(self.widget_5)
        self.b11.setObjectName("b11")
        self.gridLayout_4.addWidget(self.b11, 2, 1, 1, 1)
        self.b13 = QtGui.QPushButton(self.widget_5)
        self.b13.setObjectName("b13")
        self.gridLayout_4.addWidget(self.b13, 2, 3, 1, 1)
        self.b5 = QtGui.QPushButton(self.widget_5)
        self.b5.setObjectName("b5")
        self.gridLayout_4.addWidget(self.b5, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_5)
        self.gridLayout.addWidget(self.widget_2, 0, 1, 3, 5)
        self.widget_3 = QtGui.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.b_new_game = QtGui.QPushButton(self.widget_3)
        self.b_new_game.setObjectName("b_new_game")
        self.gridLayout_3.addWidget(self.b_new_game, 0, 0, 1, 1)
        self.spacer_2 = QtGui.QWidget(self.widget_3)
        self.spacer_2.setObjectName("spacer_2")
        self.gridLayout_3.addWidget(self.spacer_2, 0, 1, 1, 1)
        self.b_end = QtGui.QPushButton(self.widget_3)
        self.b_end.setObjectName("b_end")
        self.gridLayout_3.addWidget(self.b_end, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.widget_3, 3, 1, 1, 5)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.l_open = QtGui.QLabel(self.widget)
        self.l_open.setObjectName("l_open")
        self.gridLayout_2.addWidget(self.l_open, 0, 0, 1, 1)
        self.v_open = QtGui.QLabel(self.widget)
        self.v_open.setObjectName("v_open")
        self.gridLayout_2.addWidget(self.v_open, 0, 1, 1, 1)
        self.l_correct = QtGui.QLabel(self.widget)
        self.l_correct.setObjectName("l_correct")
        self.gridLayout_2.addWidget(self.l_correct, 1, 0, 1, 1)
        self.v_correct = QtGui.QLabel(self.widget)
        self.v_correct.setObjectName("v_correct")
        self.gridLayout_2.addWidget(self.v_correct, 1, 1, 1, 1)
        self.l_wrong = QtGui.QLabel(self.widget)
        self.l_wrong.setObjectName("l_wrong")
        self.gridLayout_2.addWidget(self.l_wrong, 2, 0, 1, 1)
        self.v_wrong = QtGui.QLabel(self.widget)
        self.v_wrong.setObjectName("v_wrong")
        self.gridLayout_2.addWidget(self.v_wrong, 2, 1, 1, 1)
        self.l_total = QtGui.QLabel(self.widget)
        self.l_total.setObjectName("l_total")
        self.gridLayout_2.addWidget(self.l_total, 3, 0, 1, 1)
        self.v_total = QtGui.QLabel(self.widget)
        self.v_total.setObjectName("v_total")
        self.gridLayout_2.addWidget(self.v_total, 3, 1, 1, 1)
        self.l_games = QtGui.QLabel(self.widget)
        self.l_games.setObjectName("l_games")
        self.gridLayout_2.addWidget(self.l_games, 4, 0, 1, 1)
        self.v_games = QtGui.QLabel(self.widget)
        self.v_games.setObjectName("v_games")
        self.gridLayout_2.addWidget(self.v_games, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 4, 1)
        self.spacer = QtGui.QWidget(self.centralwidget)
        self.spacer.setObjectName("spacer")
        self.gridLayout.addWidget(self.spacer, 0, 6, 4, 1)
        MyGame.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MyGame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1272, 26))
        self.menubar.setObjectName("menubar")
        MyGame.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MyGame)
        self.statusbar.setObjectName("statusbar")
        MyGame.setStatusBar(self.statusbar)

        self.retranslateUi(MyGame)
        QtCore.QMetaObject.connectSlotsByName(MyGame)

    def retranslateUi(self, MyGame):
        MyGame.setWindowTitle(QtGui.QApplication.translate("MyGame", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MyGame", "<h1>Push the buttons in ascending order!</h1>", None, QtGui.QApplication.UnicodeUTF8))
        self.b0.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b1.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b8.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b14.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b10.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b7.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b12.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b9.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b4.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b3.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b2.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b6.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b11.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b13.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b5.setText(QtGui.QApplication.translate("MyGame", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.b_new_game.setText(QtGui.QApplication.translate("MyGame", "New game", None, QtGui.QApplication.UnicodeUTF8))
        self.b_end.setText(QtGui.QApplication.translate("MyGame", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.l_open.setText(QtGui.QApplication.translate("MyGame", "<b>open</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.v_open.setText(QtGui.QApplication.translate("MyGame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.l_correct.setText(QtGui.QApplication.translate("MyGame", "<b>correct</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.v_correct.setText(QtGui.QApplication.translate("MyGame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.l_wrong.setText(QtGui.QApplication.translate("MyGame", "<b>wrong</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.v_wrong.setText(QtGui.QApplication.translate("MyGame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.l_total.setText(QtGui.QApplication.translate("MyGame", "<b>total</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.v_total.setText(QtGui.QApplication.translate("MyGame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.l_games.setText(QtGui.QApplication.translate("MyGame", "<b>Games</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.v_games.setText(QtGui.QApplication.translate("MyGame", "0", None, QtGui.QApplication.UnicodeUTF8))

